"use client";
import {useEffect,useMemo,useState} from "react";
import {AnimatePresence,motion} from "framer-motion";
import {ArrowDownToLine,ArrowUpFromLine,Bell,ChevronRight,Crown,Home,ShieldCheck,Users,WalletCards,Copy,History,Settings,LogOut,Image as ImageIcon,Radio,Sparkles,Headphones,LockKeyhole,TrendingUp,Zap,Plus,Trash2,Landmark,Smartphone,BadgePercent,SlidersHorizontal} from "lucide-react";
import {adminApproveDeposit,adminApproveWithdrawal,adminCreatePlan,adminList,adminTogglePlan,buyVip,claimVip,createDeposit,createWithdrawal,getActiveVipPlans,getAllVipPlans,getMyVip,getReferrals,getTransactions,getUser,getPublicSettings,savePublicSettings,uploadDepositProof} from "@/lib/firestore";
import {authenticateTelegram} from "@/lib/auth";
import type {TransactionDoc,UserDoc,VipPlanDoc,VipPurchaseDoc} from "@/lib/models";

type Tab="home"|"vip"|"referral"|"wallet"|"admin";
type TgUser={id:number;first_name:string;username?:string;photo_url?:string};
declare global{interface Window{Telegram?:{WebApp?:{initData?:string;initDataUnsafe?:{user?:TgUser;start_param?:string};ready?:()=>void;expand?:()=>void;setHeaderColor?:(c:string)=>void;setBackgroundColor?:(c:string)=>void;openTelegramLink?:(u:string)=>void;showAlert?:(m:string)=>void}}}}

const usd=(n:number)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})+" AFN";
const toast=(m:string)=>{const showAlert=window.Telegram?.WebApp?.showAlert;if(showAlert){showAlert(m);return;}window.alert(m);};

export default function App(){
 const [tab,setTab]=useState<Tab>("home"),[allowed,setAllowed]=useState<boolean|null>(null),[tg,setTg]=useState<TgUser|null>(null),[user,setUser]=useState<UserDoc|null>(null),[plans,setPlans]=useState<VipPlanDoc[]>([]),[vips,setVips]=useState<VipPurchaseDoc[]>([]),[txs,setTxs]=useState<TransactionDoc[]>([]),[refs,setRefs]=useState<any[]>([]),[settings,setSettings]=useState<any>({currency:"AFN",currencySymbol:"؋",minDeposit:100,maxDeposit:100000,minWithdraw:100,maxWithdraw:50000,referralPercent:5,depositMethods:[{id:"hesab-pay",name:"HESAB PAY",details:"Enter HESAB PAY number / payment reference",active:true},{id:"momo",name:"MOMO",details:"Enter MOMO number / payment reference",active:true}],withdrawMethods:[{id:"hesab-pay",name:"HESAB PAY",details:"Enter your HESAB PAY account number",active:true},{id:"momo",name:"MOMO",details:"Enter your MOMO account number",active:true}],channels:[]}),[busy,setBusy]=useState(false);
 const adminId=Number(process.env.NEXT_PUBLIC_ADMIN_TELEGRAM_ID||"6589090462");
 const isAdmin=!!tg && (tg.id===adminId || user?.isAdmin===true);
 async function refresh(id:number){const [u,p,v,t,r,s]=await Promise.all([getUser(id),getActiveVipPlans(),getMyVip(id),getTransactions(id),getReferrals(id),getPublicSettings()]);setUser(u);setPlans(p);setVips(v);setTxs(t);setRefs(r);if(s)setSettings(s)}
 useEffect(()=>{(async()=>{const w=window.Telegram?.WebApp;const telegramUser=w?.initDataUnsafe?.user;if(telegramUser?.id){w?.ready?.();w?.expand?.();w?.setHeaderColor?.("#080808");w?.setBackgroundColor?.("#080808");setAllowed(true);setTg(telegramUser);const raw=w?.initDataUnsafe?.start_param||"";const ref=raw.startsWith("ref_")?Number(raw.slice(4)):null;await authenticateTelegram(w?.initData||"",ref);await refresh(telegramUser.id);return}const webUser:TgUser={id:0,first_name:"AFGlion Guest",username:"web_guest"};setAllowed(true);setTg(webUser);try{const [publicPlans,publicSettings]=await Promise.all([getActiveVipPlans(),getPublicSettings()]);setPlans(publicPlans);if(publicSettings)setSettings(publicSettings)}catch{} })().catch(e=>toast(e.message))},[]);
 const page=useMemo(()=>{if(!tg)return null;const props={tg,user,plans,vips,txs,refs,settings,refresh:()=>refresh(tg.id),setTab,setBusy,busy};if(tab==="vip")return <Vip {...props}/>;if(tab==="referral")return <Referral {...props}/>;if(tab==="wallet")return <Wallet {...props}/>;if(tab==="admin"&&isAdmin)return <Admin tg={tg} settings={settings} refresh={()=>refresh(tg.id)} onBack={()=>setTab("home")}/>;return <Dashboard {...props}/>},[tab,tg,user,plans,vips,txs,refs,settings,busy,isAdmin]);
 if(allowed===null)return <main className="gate"><div className="lion-loader">🦁</div><p>Opening AFGlion...</p></main>;
 return <main className="app-shell"><header className="topbar"><div className="brand"><div className="brand-icon">🦁</div><div><b>AFG<span>lion</span></b><small>Premium Finance</small></div></div><div className="top-actions">{isAdmin&&<button className="admin-chip" onClick={()=>setTab("admin")}><Settings size={14}/> Admin Panel</button>}<button className="icon-button"><Bell size={18}/></button></div></header>
 <AnimatePresence mode="wait"><motion.section key={tab} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="page">{page}</motion.section></AnimatePresence>
 {tab!=="admin"&&<nav className="bottom-nav"><Nav a={tab==="home"} l="Home" i={<Home/>} c={()=>setTab("home")}/><Nav a={tab==="vip"} l="VIP" i={<Crown/>} c={()=>setTab("vip")}/><Nav a={tab==="referral"} l="Referral" i={<Users/>} c={()=>setTab("referral")}/><Nav a={tab==="wallet"} l="Wallet" i={<WalletCards/>} c={()=>setTab("wallet")}/></nav>}</main>
}
function Nav({a,l,i,c}:{a:boolean;l:string;i:React.ReactNode;c:()=>void}){return <button className={"nav-item "+(a?"active":"")} onClick={c}>{i}<span>{l}</span></button>}
function Dashboard(p:any){
 const active=p.vips.find((v:VipPurchaseDoc)=>v.status==="active");
 const totalPortfolio=Number(p.user?.balance||0)+Number(p.user?.totalVipProfit||0)+Number(p.user?.referralEarnings||0);
 const daysLeft=active?Math.max(0,Math.ceil((active.endAt-Date.now())/86400000)):0;
 const vipProgress=active?Math.min(100,Math.max(0,((Date.now()-active.startAt)/(active.endAt-active.startAt))*100)):0;
 return <><div className="hello"><div><small>Welcome back</small><h1>{p.tg.first_name} 👋</h1><span className="verified-line"><ShieldCheck/> Verified AFGlion member</span></div><div className="avatar">{p.tg.photo_url?<img src={p.tg.photo_url}/>: "🦁"}</div></div>
 <div className="portfolio-hero"><div className="hero-orb"/><div className="portfolio-top"><span>MY PORTFOLIO</span><span className="live-dot">● LIVE</span></div><h2>{usd(totalPortfolio)}</h2><p>Total account value</p><div className="portfolio-mini"><div><span>Available</span><b>{usd(p.user?.balance)}</b></div><div><span>Total earned</span><b>{usd(Number(p.user?.totalVipProfit||0)+Number(p.user?.referralEarnings||0))}</b></div></div></div>
 <div className="quick-grid"><button onClick={()=>p.setTab("wallet")}><span><ArrowDownToLine/></span><b>Deposit</b><small>Add funds</small></button><button onClick={()=>p.setTab("wallet")}><span><ArrowUpFromLine/></span><b>Withdraw</b><small>Cash out</small></button><button onClick={()=>p.setTab("vip")}><span><Crown/></span><b>VIP</b><small>Earn daily</small></button><button onClick={()=>p.setTab("referral")}><span><Users/></span><b>Invite</b><small>Get rewards</small></button></div>
 {p.settings?.announcement&&<div className="announcement premium"><Bell/><div><b>AFGlion Announcement</b><span>{p.settings.announcement}</span></div><ChevronRight/></div>}
 <Title t="VIP Center" a="All packages" c={()=>p.setTab("vip")}/>{active?<div className="vip-progress-card"><div className="vip-progress-head"><div className="vip-crown"><Crown/></div><div><small>ACTIVE PACKAGE</small><b>{active.planName}</b></div><strong>{usd(active.dailyReward)}<small>/day</small></strong></div><div className="progress-track"><i style={{width:vipProgress+"%"}}/></div><div className="progress-meta"><span>{daysLeft} days remaining</span><span>{usd(active.claimedReward)} claimed</span></div></div>:<div className="upgrade-banner"><div><span className="eyebrow">START EARNING</span><h3>Unlock daily VIP rewards</h3><p>Choose a package that fits your balance and start your AFGlion journey.</p><button onClick={()=>p.setTab("vip")}>Explore VIP <ChevronRight/></button></div><Crown/></div>}
 <div className="stats-grid rich"><Stat t="VIP Profit" v={usd(p.user?.totalVipProfit)} h="Lifetime earnings"/><Stat t="Referral Rewards" v={usd(p.user?.referralEarnings)} h={p.refs.length+" invited users"}/></div>
 <div className="referral-banner" onClick={()=>p.setTab("referral")}><div className="ref-icon"><Users/></div><div><small>GROW TOGETHER</small><b>Invite friends. Earn rewards.</b><span>Your personal referral network is ready.</span></div><ChevronRight/></div>
 <Title t="AFGlion Community"/>{p.settings?.channels?.length>0?<div className="channel-grid">{p.settings.channels.slice(0,2).map((x:any)=><button key={x.url} onClick={()=>{if(window.Telegram?.WebApp?.openTelegramLink)window.Telegram.WebApp.openTelegramLink(x.url);else window.open(x.url,"_blank")}}><Radio/><div><b>{x.name}</b><span>Official community</span></div><ChevronRight/></button>)}</div>:<div className="channel-empty"><Radio/><div><b>Official channels</b><span>Add up to two channels from Admin Panel → Settings.</span></div></div>}
 <Title t="Account Center"/><div className="account-center"><div><span><LockKeyhole/></span><b>Security</b><small>Protected account</small></div><div><span><Headphones/></span><b>Support</b><small>Get assistance</small></div><div><span><TrendingUp/></span><b>Activity</b><small>{p.txs.length} records</small></div></div>
 <Title t="Recent Activity" a={p.txs.length>3?"View wallet":undefined} c={()=>p.setTab("wallet")}/>{p.txs.slice(0,4).map((x:TransactionDoc)=><Tx key={x.id} x={x}/>)}{!p.txs.length&&<Empty icon={<History/>} title="Your journey starts here" text="Deposits, VIP rewards and withdrawals will appear here."/>}
 <div className="trust-strip"><ShieldCheck/><div><b>AFGlion Secure</b><span>Manual payment review • Account activity tracking</span></div><Sparkles/></div></>
}
function Vip(p:any){
 const active=p.vips.filter((x:VipPurchaseDoc)=>x.status==="active");
 const earned=p.vips.reduce((s:number,x:VipPurchaseDoc)=>s+Number(x.claimedReward||0),0);
 async function buy(plan:VipPlanDoc){try{p.setBusy(true);await buyVip(p.tg.id,plan);await p.refresh();toast("VIP package activated.")}catch(e:any){toast(e.message)}finally{p.setBusy(false)}}
 async function claim(v:VipPurchaseDoc){try{p.setBusy(true);const r=await claimVip(p.tg.id,v.id!);await p.refresh();toast("Claimed "+usd(r))}catch(e:any){toast(e.message)}finally{p.setBusy(false)}}
 return <><div className="page-title"><small>AFGLION MEMBERSHIP</small><h1>VIP Center 👑</h1></div>
 <div className="vip-main-hero"><div><span>PREMIUM MEMBERSHIP</span><h2>Rise through the Lion ranks.</h2><p>Activate a package, track its cycle and collect available daily rewards.</p></div><Crown/></div>
 <div className="three-metrics"><Stat t="Active Plans" v={String(active.length)} h="Running now"/><Stat t="VIP Earned" v={usd(earned)} h="Total claimed"/><Stat t="Packages" v={String(p.plans.length)} h="Available"/></div>
 {active.length>0&&<><Title t="My Active Membership"/>{active.map((v:VipPurchaseDoc)=>{const pct=Math.min(100,Math.max(0,((Date.now()-v.startAt)/(v.endAt-v.startAt))*100));const left=Math.max(0,Math.ceil((v.endAt-Date.now())/86400000));return <div className="membership-card" key={v.id}><div className="membership-top"><div className="vip-crown"><Crown/></div><div><small>ACTIVE VIP</small><h3>{v.planName}</h3></div><span className="active-badge">ACTIVE</span></div><div className="membership-numbers"><div><span>Daily Reward</span><b>{usd(v.dailyReward)}</b></div><div><span>Claimed</span><b>{usd(v.claimedReward)}</b></div><div><span>Days Left</span><b>{left}</b></div></div><div className="progress-track"><i style={{width:pct+"%"}}/></div><button className="gold-button" disabled={p.busy} onClick={()=>claim(v)}><Zap/> Claim Available Reward</button></div>})}</>}
 <Title t="Choose Your Package"/><div className="plans">{p.plans.map((x:VipPlanDoc)=><div className="plan-card upgraded" key={x.id}><div className="plan-top"><div><span className="pill">{x.badge||"VIP"}</span><h3>{x.name}</h3><small>{x.durationDays}-day membership cycle</small></div><Crown/></div><div className="plan-price"><b>{usd(x.price)}</b><span>activation price</span></div><div className="plan-details"><div><span>Daily reward</span><b>{usd(x.dailyReward)}</b></div><div><span>Full duration</span><b>{x.durationDays} days</b></div><div><span>Potential cycle reward</span><b>{usd(x.dailyReward*x.durationDays)}</b></div></div><button disabled={p.busy} onClick={()=>buy(x)}>Stake / Activate {x.name} <ChevronRight/></button></div>)}{!p.plans.length&&<Empty icon={<Crown/>} title="Packages coming soon" text="New AFGlion VIP levels will appear here."/>}</div>
 <div className="info-panel"><ShieldCheck/><div><b>How VIP works</b><span>Fund your wallet → choose an active package → track the cycle → claim available rewards from your membership.</span></div></div>
 <div className="trust-strip"><LockKeyhole/><div><b>Membership records</b><span>Every purchase and reward is recorded in your account activity.</span></div><Sparkles/></div></>
}
function Referral(p:any){
 const bot=process.env.NEXT_PUBLIC_BOT_USERNAME||"Afglionbot";const link=`https://t.me/${bot}?startapp=ref_${p.tg.id}`;
 const rewarded=p.refs.filter((r:any)=>r.status==="rewarded").length;const progress=Math.min(100,(p.refs.length/10)*100);
 async function copy(){await navigator.clipboard.writeText(link);toast("Referral link copied.")}
 function share(){const u=`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent("Join me on AFGlion")}`;if(window.Telegram?.WebApp?.openTelegramLink)window.Telegram.WebApp.openTelegramLink(u);else window.open(u,"_blank")}
 return <><div className="page-title"><small>AFGLION NETWORK</small><h1>Referral Hub 👥</h1></div>
 <div className="referral-hero"><div className="network-orb"/><span>YOUR NETWORK REWARDS</span><h2>{usd(p.user?.referralEarnings)}</h2><p>Build your circle and grow together with AFGlion.</p><div className="referral-hero-stats"><div><b>{p.refs.length}</b><span>Total invites</span></div><div><b>{rewarded}</b><span>Qualified</span></div><div><b>{Math.max(0,p.refs.length-rewarded)}</b><span>Pending</span></div></div></div>
 <div className="commission-card"><BadgePercent/><div><small>REFERRAL COMMISSION</small><b>{Number(p.settings?.referralPercent||0)}% per VIP activation</b><span>Admin controls this percentage from Settings.</span></div></div><div className="network-progress"><div className="network-head"><div><small>NETWORK MILESTONE</small><b>{p.refs.length} / 10 referrals</b></div><Users/></div><div className="progress-track"><i style={{width:progress+"%"}}/></div><span>Invite {Math.max(0,10-p.refs.length)} more to reach your first network milestone.</span></div>
 <Title t="Invite Friends"/><div className="share-card premium-share"><b>Your personal invitation link</b><p>Anyone who joins through this link will be connected to your network.</p><div className="link-box"><span>{link}</span><button onClick={copy}><Copy/></button></div><div className="share-actions"><button onClick={copy}><Copy/> Copy Link</button><button onClick={share}><Users/> Share on Telegram</button></div></div>
 <Title t="How It Works"/><div className="steps-row"><div><span>1</span><b>Share</b><small>Send your link</small></div><i/><div><span>2</span><b>Friend joins</b><small>Account connects</small></div><i/><div><span>3</span><b>Reward</b><small>Track earnings</small></div></div>
 <Title t="Network Overview"/><div className="stats-grid rich"><Stat t="Total Referrals" v={String(p.refs.length)} h="People in network"/><Stat t="Referral Earnings" v={usd(p.user?.referralEarnings)} h="Lifetime rewards"/></div>
 <Title t="My Referrals"/>{p.refs.slice(0,20).map((r:any,i:number)=><div className="ref-person" key={r.id}><div className="ref-avatar">{String(i+1).padStart(2,"0")}</div><div><b>User #{r.invitedTelegramId}</b><span>Joined your AFGlion network</span></div><div className="ref-status"><small>{r.status}</small><b>{usd(r.reward)}</b></div></div>)}{!p.refs.length&&<Empty icon={<Users/>} title="Your network is waiting" text="Copy your referral link and invite your first friend."/>}
 <div className="info-panel"><Sparkles/><div><b>Grow your AFGlion circle</b><span>Your referral totals, qualification status and rewards stay visible here as your network grows.</span></div></div></>
}
function Wallet(p:any){
 const [mode,setMode]=useState<"deposit"|"withdraw"|null>(null),[amount,setAmount]=useState(""),[method,setMethod]=useState(""),[ref,setRef]=useState(""),[proof,setProof]=useState<File|null>(null);
 const methods=(mode==="deposit"?p.settings?.depositMethods:p.settings?.withdrawMethods)?.filter((x:any)=>x.active!==false)||[];
 const incoming=p.txs.filter((x:TransactionDoc)=>x.amount>0).reduce((s:number,x:TransactionDoc)=>s+x.amount,0),outgoing=Math.abs(p.txs.filter((x:TransactionDoc)=>x.amount<0).reduce((s:number,x:TransactionDoc)=>s+x.amount,0));
 useEffect(()=>{if(mode&&methods.length)setMethod(methods[0].id)},[mode,methods.length]);
 async function submit(e:React.FormEvent){e.preventDefault();try{p.setBusy(true);const n=Number(amount);if(!n||n<=0)throw new Error("Enter a valid amount");const min=Number(mode==="deposit"?p.settings?.minDeposit||100:p.settings?.minWithdraw||100),max=Number(mode==="deposit"?p.settings?.maxDeposit||100000:p.settings?.maxWithdraw||50000);if(n<min||n>max)throw new Error(`Amount must be between ${min} and ${max} ${p.settings?.currency||"AFN"}`);const selected=methods.find((x:any)=>x.id===method);if(!selected)throw new Error("Select a payment method");if(mode==="deposit"){if(!proof)throw new Error("Payment proof image is required");const proofUrl=await uploadDepositProof(p.tg.id,proof);await createDeposit({userTelegramId:p.tg.id,amount:n,method:selected.name,txid:ref,proofUrl})}else await createWithdrawal({userTelegramId:p.tg.id,amount:n,method:selected.name,destination:ref});setMode(null);setAmount("");setRef("");setProof(null);await p.refresh();toast("Request submitted for admin review.")}catch(e:any){toast(e.message)}finally{p.setBusy(false)}}
 return <><div className="page-title"><small>AFGLION MONEY CENTER</small><h1>Wallet 💳</h1></div>
 <div className="wallet-premium"><div className="wallet-top"><span>AVAILABLE BALANCE</span><ShieldCheck/></div><h2>{p.settings?.currencySymbol||"$"}{Number(p.user?.balance||0).toFixed(2)}</h2><small>{p.settings?.currency||"USD"} • AFGlion Wallet</small><div className="wallet-summary"><div><span>Total In</span><b>+{usd(incoming)}</b></div><div><span>Total Out</span><b>{usd(outgoing)}</b></div></div></div>
 <div className="wallet-actions-grid premium-actions"><button onClick={()=>setMode("deposit")}><span><ArrowDownToLine/></span><b>Deposit</b><small>Add money manually</small></button><button onClick={()=>setMode("withdraw")}><span><ArrowUpFromLine/></span><b>Withdraw</b><small>Request payout</small></button></div>
 <div className="limit-strip"><SlidersHorizontal/><div><b>Deposit {Number(p.settings?.minDeposit||100).toLocaleString()}–{Number(p.settings?.maxDeposit||100000).toLocaleString()} AFN</b><span>Withdraw {Number(p.settings?.minWithdraw||100).toLocaleString()}–{Number(p.settings?.maxWithdraw||50000).toLocaleString()} AFN</span></div></div><div className="wallet-strip"><LockKeyhole/><div><b>Manual review protection</b><span>Payment requests are reviewed by AFGlion administration before approval.</span></div></div>
 {mode&&<form className="wallet-form premium-form" onSubmit={submit}><div className="form-head"><div><small>{mode==="deposit"?"FUND YOUR WALLET":"REQUEST PAYOUT"}</small><b>{mode==="deposit"?"New Deposit":"New Withdrawal"}</b></div><button type="button" onClick={()=>setMode(null)}>×</button></div><label>Amount ({p.settings?.currency||"USD"})</label><input inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/><label>Payment Method</label><select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select>{methods.find((x:any)=>x.id===method)?.details&&<div className="method-details">{methods.find((x:any)=>x.id===method)?.details}</div>}<label>{mode==="deposit"?"TXID / payment reference":"Wallet address / account"}</label><input required value={ref} onChange={e=>setRef(e.target.value)} placeholder="Enter payment details"/>{mode==="deposit"&&<><label>Payment Proof *</label><label className="proof-picker"><ImageIcon/><div><b>{proof?proof.name:"Upload payment screenshot"}</b><span>JPG, PNG or WEBP • max 5 MB</span></div><input type="file" accept="image/*" required onChange={e=>setProof(e.target.files?.[0]||null)}/></label></>}<div className="notice"><ShieldCheck/> Admin verification required before completion</div><button disabled={p.busy} className="gold-button">Submit {mode==="deposit"?"Deposit":"Withdrawal"}</button></form>}
 <Title t="Payment Methods"/><div className="payment-method-grid">{[...(p.settings?.depositMethods||[]),...(p.settings?.withdrawMethods||[])].filter((x:any,i:number,a:any[])=>x.active!==false&&a.findIndex(y=>y.id===x.id)===i).slice(0,4).map((x:any)=><div key={x.id}><WalletCards/><div><b>{x.name}</b><span>Available</span></div><i>●</i></div>)}</div>
 <Title t="Transaction Summary"/><div className="three-metrics wallet-metrics"><Stat t="Transactions" v={String(p.txs.length)} h="All activity"/><Stat t="Money In" v={usd(incoming)} h="Credits"/><Stat t="Money Out" v={usd(outgoing)} h="Debits"/></div>
 <Title t="Recent Transactions"/>{p.txs.slice(0,12).map((x:TransactionDoc)=><Tx key={x.id} x={x}/>)}{!p.txs.length&&<Empty icon={<WalletCards/>} title="No wallet activity" text="Your deposits, withdrawals and rewards will be listed here."/>}
 <div className="info-panel"><ShieldCheck/><div><b>Wallet security</b><span>Always verify payment details before sending funds and keep your payment proof until approval.</span></div></div></>
}
function Admin({tg,settings,refresh,onBack}:{tg:TgUser;settings:any;refresh:()=>Promise<void>;onBack:()=>void}){
 const defaultDeposit=[{id:"hesab-pay",name:"HESAB PAY",details:"Enter HESAB PAY number / payment reference",active:true},{id:"momo",name:"MOMO",details:"Enter MOMO number / payment reference",active:true}];
 const defaultWithdraw=[{id:"hesab-pay",name:"HESAB PAY",details:"Enter your HESAB PAY account number",active:true},{id:"momo",name:"MOMO",details:"Enter your MOMO account number",active:true}];
 const [section,setSection]=useState("overview"),[items,setItems]=useState<any[]>([]),[plans,setPlans]=useState<VipPlanDoc[]>([]),[form,setForm]=useState({name:"",price:"",daily:"",days:"",badge:"VIP"}),[busy,setBusy]=useState(false),[cfg,setCfg]=useState<any>({currency:settings?.currency||"AFN",currencySymbol:settings?.currencySymbol||"؋",minDeposit:String(settings?.minDeposit??100),maxDeposit:String(settings?.maxDeposit??100000),minWithdraw:String(settings?.minWithdraw??100),maxWithdraw:String(settings?.maxWithdraw??50000),referralPercent:String(settings?.referralPercent??5),announcement:settings?.announcement||"",depositMethods:settings?.depositMethods?.length?settings.depositMethods:defaultDeposit,withdrawMethods:settings?.withdrawMethods?.length?settings.withdrawMethods:defaultWithdraw,channel1Name:settings?.channels?.[0]?.name||"",channel1Url:settings?.channels?.[0]?.url||"",channel2Name:settings?.channels?.[1]?.name||"",channel2Url:settings?.channels?.[1]?.url||""});
 async function load(s=section){setSection(s);try{if(s==="vip")setPlans(await getAllVipPlans());else if(s!=="overview"&&s!=="settings")setItems(await adminList(s))}catch(e:any){toast(e.message)}}
 useEffect(()=>{load("overview")},[]);
 async function addPlan(e:React.FormEvent){e.preventDefault();try{setBusy(true);await adminCreatePlan(tg.id,{name:form.name,price:Number(form.price),dailyReward:Number(form.daily),durationDays:Number(form.days),badge:form.badge,active:true});setForm({name:"",price:"",daily:"",days:"",badge:"VIP"});await load("vip");toast("VIP package created.")}catch(e:any){toast(e.message)}finally{setBusy(false)}}
 async function review(kind:string,id:string,yes:boolean){try{setBusy(true);kind==="deposits"?await adminApproveDeposit(tg.id,id,yes):await adminApproveWithdrawal(tg.id,id,yes);await load(kind);toast(yes?"Approved.":"Rejected.")}catch(e:any){toast(e.message)}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();try{setBusy(true);const referral=Math.max(0,Math.min(100,Number(cfg.referralPercent||0)));await savePublicSettings({currency:cfg.currency||"AFN",currencySymbol:cfg.currencySymbol||"؋",minDeposit:Number(cfg.minDeposit||0),maxDeposit:Number(cfg.maxDeposit||0),minWithdraw:Number(cfg.minWithdraw||0),maxWithdraw:Number(cfg.maxWithdraw||0),referralPercent:referral,announcement:cfg.announcement,depositMethods:cfg.depositMethods,withdrawMethods:cfg.withdrawMethods,channels:[{name:cfg.channel1Name.trim(),url:cfg.channel1Url.trim()},{name:cfg.channel2Name.trim(),url:cfg.channel2Url.trim()}].filter(x=>x.name&&x.url).slice(0,2),botUsername:"Afglionbot"});await refresh();toast("Settings saved.")}catch(e:any){toast(e.message)}finally{setBusy(false)}}
 return <><div className="admin-head"><div><small>AFGlion Control Center</small><h1>Admin Panel 🦁</h1></div><button className="admin-back" onClick={onBack}><LogOut/> Back</button></div>
 <div className="admin-tabs"><button onClick={()=>load("overview")}>Overview</button><button onClick={()=>load("users")}>Users</button><button onClick={()=>load("vip")}>VIP</button><button onClick={()=>load("deposits")}>Deposits</button><button onClick={()=>load("withdrawals")}>Withdraw</button><button onClick={()=>load("settings")}>Settings</button></div>
 {section==="settings"&&<form className="wallet-form admin-settings" onSubmit={save}><div className="settings-title"><Settings/><div><b>App & Payment Settings</b><span>Control money limits, methods and referral commission.</span></div></div>
 <label>Currency</label><div className="two"><input value={cfg.currency} onChange={e=>setCfg({...cfg,currency:e.target.value})} placeholder="AFN"/><input value={cfg.currencySymbol} onChange={e=>setCfg({...cfg,currencySymbol:e.target.value})} placeholder="؋"/></div>
 <label>Deposit limits (AFN)</label><div className="two"><input inputMode="numeric" value={cfg.minDeposit} onChange={e=>setCfg({...cfg,minDeposit:e.target.value})} placeholder="Minimum"/><input inputMode="numeric" value={cfg.maxDeposit} onChange={e=>setCfg({...cfg,maxDeposit:e.target.value})} placeholder="Maximum"/></div>
 <label>Withdrawal limits (AFN)</label><div className="two"><input inputMode="numeric" value={cfg.minWithdraw} onChange={e=>setCfg({...cfg,minWithdraw:e.target.value})} placeholder="Minimum"/><input inputMode="numeric" value={cfg.maxWithdraw} onChange={e=>setCfg({...cfg,maxWithdraw:e.target.value})} placeholder="Maximum"/></div>
 <label>Referral commission %</label><div className="percent-field"><BadgePercent/><input inputMode="decimal" value={cfg.referralPercent} onChange={e=>setCfg({...cfg,referralPercent:e.target.value})} placeholder="5"/></div>
 <label>Announcement</label><input value={cfg.announcement} onChange={e=>setCfg({...cfg,announcement:e.target.value})} placeholder="Dashboard announcement"/>
 <MethodEditor title="Deposit Methods" icon={<Landmark/>} items={cfg.depositMethods} onChange={(v:any[])=>setCfg({...cfg,depositMethods:v})}/>
 <MethodEditor title="Withdrawal Methods" icon={<Smartphone/>} items={cfg.withdrawMethods} onChange={(v:any[])=>setCfg({...cfg,withdrawMethods:v})}/>
 <label>Official Channel 1</label><div className="two"><input value={cfg.channel1Name} onChange={e=>setCfg({...cfg,channel1Name:e.target.value})} placeholder="Channel name"/><input value={cfg.channel1Url} onChange={e=>setCfg({...cfg,channel1Url:e.target.value})} placeholder="https://t.me/channel"/></div>
 <label>Official Channel 2</label><div className="two"><input value={cfg.channel2Name} onChange={e=>setCfg({...cfg,channel2Name:e.target.value})} placeholder="Channel name"/><input value={cfg.channel2Url} onChange={e=>setCfg({...cfg,channel2Url:e.target.value})} placeholder="https://t.me/channel"/></div>
 <button className="gold-button" disabled={busy}>Save All Settings</button></form>}
 {section==="overview"&&<div className="admin-grid"><Stat t="Management" v="Live" h="Firebase connected"/><Stat t="Referral %" v={String(cfg.referralPercent)+"%"} h="VIP commission"/><Stat t="Deposit Min" v={usd(Number(cfg.minDeposit))} h="Admin controlled"/><Stat t="Withdraw Min" v={usd(Number(cfg.minWithdraw))} h="Admin controlled"/><div className="admin-note"><Settings/><b>Control Center Ready</b><span>Manage users, VIP packages, payment methods and manual requests.</span></div></div>}
 {section==="vip"&&<><form className="wallet-form" onSubmit={addPlan}><b>Create VIP / Stake Package</b><input required placeholder="Package name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div className="two"><input required inputMode="decimal" placeholder="Price AFN" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input required inputMode="decimal" placeholder="Daily reward AFN" value={form.daily} onChange={e=>setForm({...form,daily:e.target.value})}/></div><div className="two"><input required inputMode="numeric" placeholder="Days" value={form.days} onChange={e=>setForm({...form,days:e.target.value})}/><input placeholder="Badge" value={form.badge} onChange={e=>setForm({...form,badge:e.target.value})}/></div><button disabled={busy} className="gold-button">Create Package</button></form>{plans.map(x=><div className="admin-row" key={x.id}><Crown/><div><b>{x.name}</b><span>{usd(x.price)} • {usd(x.dailyReward)}/day • {x.durationDays}d</span></div><button onClick={async()=>{await adminTogglePlan(x.id!,!x.active);load("vip")}}>{x.active?"Disable":"Enable"}</button></div>)}</>}
 {section!=="overview"&&section!=="vip"&&section!=="settings"&&<>{items.map(x=><div className="admin-row" key={x.id}><WalletCards/><div><b>{x.firstName||x.method||("User #"+x.userTelegramId)}</b><span>{x.status||("@"+(x.username||"no_username"))} {x.amount!=null?" • "+usd(x.amount):""}</span>{section==="deposits"&&x.proofUrl&&<a className="proof-link" href={x.proofUrl} target="_blank">View proof</a>}</div>{(section==="deposits"||section==="withdrawals")&&x.status==="pending"?<div className="review"><button disabled={busy} onClick={()=>review(section,x.id,true)}>✓</button><button disabled={busy} onClick={()=>review(section,x.id,false)}>×</button></div>:null}</div>)}{!items.length&&<Empty icon={<WalletCards/>} title="Nothing here" text="No records found in this section."/>}</>}</>
}
function MethodEditor({title,icon,items,onChange}:{title:string;icon:React.ReactNode;items:any[];onChange:(v:any[])=>void}){
 const add=()=>onChange([...items,{id:"method-"+Date.now(),name:"New Method",details:"",active:true}]);
 const edit=(i:number,key:string,value:any)=>onChange(items.map((x,j)=>j===i?{...x,[key]:value}:x));
 const remove=(i:number)=>onChange(items.filter((_,j)=>j!==i));
 return <div className="method-editor"><div className="method-editor-head">{icon}<b>{title}</b><button type="button" onClick={add}><Plus/> Add</button></div>{items.map((m,i)=><div className="method-edit-row" key={m.id||i}><div className="method-line"><input value={m.name||""} onChange={e=>edit(i,"name",e.target.value)} placeholder="Method name"/><label className="switch-mini"><input type="checkbox" checked={m.active!==false} onChange={e=>edit(i,"active",e.target.checked)}/><span>{m.active!==false?"On":"Off"}</span></label><button type="button" className="delete-method" onClick={()=>remove(i)}><Trash2/></button></div><input value={m.details||""} onChange={e=>edit(i,"details",e.target.value)} placeholder="Account number / instructions"/></div>)}</div>
}
function Stat({t,v,h}:{t:string;v:string;h:string}){return <div className="stat-card"><span>{t}</span><b>{v}</b><small>{h}</small></div>}
function Title({t,a,c}:{t:string;a?:string;c?:()=>void}){return <div className="section-title"><h3>{t}</h3>{a&&<button onClick={c}>{a}<ChevronRight/></button>}</div>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty-card">{icon}<b>{title}</b><span>{text}</span></div>}
function Tx({x}:{x:TransactionDoc}){return <div className="list-row"><WalletCards/><div><b>{x.type.replaceAll("_"," ")}</b><span>{new Date(x.createdAt).toLocaleDateString()} • {x.status}</span></div><strong className={x.amount>=0?"plus":"minus"}>{x.amount>=0?"+":""}{usd(x.amount)}</strong></div>}
